# configuration items
pwd: ~/track_plans
docs: docs/
xtc: gen2h.xtc
dfs_ramps_file: dfs_seq.svg
dfs_physical_file: dfs_physical.svg
dfs_logical_file: dfs_logical.svg
# spanning tree files
st_ramps_file: st_ramps.svg
st_physical_file: st_physical.svg
st_logical_file: st_logical.svg
show_only: False